[quota]
target = true
minimal_score = 5

[camera]
id = "camera"
position = [8.63275, 18.63720, 19.12090]
lookdir = [0.70957, -0.61891, 0.33685]
fov = 120

[lighting.ambient]
intensity = 0.40000
color = [255, 255, 255]

[[objects.planes]]
id = "plane1"
color = [170, 170, 170]
position = [0, 21.55000, 0]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane2"
color = [80, 80, 80]
texture = "textures/floor.jpg"
position = [-27.44161, 2.08875, -47.03945]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane3"
color = [133, 116, 95]
position = [5.00610, 5.24599, 33.66659]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane4"
color = [133, 116, 95]
position = [-2.98246, -0.19339, -0.22198]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane5"
color = [133, 116, 95]
position = [20.35066, 16.73787, -1.16790]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane6"
color = [133, 116, 95]
position = [-4.57157, -0.09982, -9.42990]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.boxes]]
id = "box1"
color = [0, 250, 0]
position = [20.01752, 17.05291, 1.50960]
dir = [-0.61225, -0.54918, 0.56882]
width = 1.46410
height = 1.46410
length = 1.46410
reflective = true
rotatable = true
movable = true
scorable = true
transparent = false

[[objects.boxes]]
id = "box2"
color = [255, 0, 0]
position = [16.15176, 4.41681, 9.76764]
dir = [-0.13924, 0.62554, 0.76766]
width = 0.30000
height = 3
length = 3
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.boxes]]
id = "box3"
color = [255, 0, 0]
position = [16.08714, 4.29823, 1.45869]
dir = [0.51346, 0.84967, -0.12008]
width = 0.30000
height = 3
length = 3
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.boxes]]
id = "box4"
color = [255, 0, 0]
position = [17.12933, 12.13151, 11.96432]
dir = [0.05678, -0.52707, -0.84792]
width = 0.30000
height = 3
length = 3
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.cones]]
id = "cone1"
color = [0, 255, 0]
position = [3.23304, 11.39742, -2.31826]
dir = [0.78904, -0.39103, 0.47382]
radius = 0.61771
height = 1.23541
reflective = true
rotatable = true
movable = true
scorable = true
transparent = false

[[beam.sources]]
id = "beam_source1"
intensity = 1
position = [3.20076, 11.44178, -4.91785]
dir = [-0.04022, -0.00727, 0.99916]
color = [255, 255, 255]
radius = 0.82217
length = 100
movable = false
rotatable = false
scorable = false
with_laser = true

[[beam.targets]]
id = "beam_target1"
position = [2.22556, 11.03264, 29.76244]
color = [255, 255, 0]
radius = 1
movable = true
scorable = true

