[quota]
target = true
minimal_score = 5

[camera]
id = "camera"
position = [-4.53545, 16.67787, 7.02493]
lookdir = [0.88386, -0.39066, -0.25724]
fov = 120

[lighting.ambient]
intensity = 0.40000
color = [255, 255, 255]

[[objects.planes]]
id = "plane1"
color = [170, 170, 170]
position = [0, 21.55000, 0]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane2"
color = [80, 80, 80]
position = [-26.36382, 0.81532, -47.83988]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane3"
color = [133, 116, 95]
position = [5.97069, 5.01130, 26.11128]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane4"
color = [133, 116, 95]
position = [-10, 0, 0]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane5"
color = [133, 116, 95]
position = [20.35066, 16.73787, -1.16790]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane6"
color = [133, 116, 95]
position = [-4.57157, -0.09982, -9.42990]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.boxes]]
id = "box1"
color = [128, 128, 128]
position = [17.03844, 17.44672, 16.45691]
dir = [0, 1, 0]
width = 13.31000
height = 13.31000
length = 0.26620
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.boxes]]
id = "box2"
color = [0, 250, 0]
position = [12.40554, 17.07973, -6.65127]
dir = [-0.61225, -0.54918, 0.56882]
width = 1.46410
height = 1.46410
length = 1.46410
reflective = true
rotatable = true
movable = true
scorable = true
transparent = false

[[objects.boxes]]
id = "box3"
color = [250, 250, 0]
position = [-8.04899, 17.77731, 23.53363]
dir = [0.06703, 0.83425, -0.54730]
width = 1.82439
height = 1.82439
length = 1.82439
reflective = true
rotatable = true
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere1"
color = [250, 0, 0]
position = [13.49366, 7.60861, 3.97844]
dir = [0.0, 1.0, 0.0]
radius = 1
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere2"
color = [250, 0, 0]
position = [2.58201, 7.66485, 1.79933]
dir = [0.0, 1.0, 0.0]
radius = 1
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere3"
color = [250, 0, 0]
position = [14.58647, 11.51812, 7.28976]
dir = [0.0, 1.0, 0.0]
radius = 1.19304
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere4"
color = [250, 0, 0]
position = [7.43902, 8.21789, 8.31929]
dir = [0.0, 1.0, 0.0]
radius = 1.03680
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere5"
color = [250, 0, 0]
position = [-0.03144, 10.71678, 7.70582]
dir = [0.0, 1.0, 0.0]
radius = 1.03680
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere6"
color = [250, 0, 0]
position = [0.39840, 13.45926, 15.50690]
dir = [0.0, 1.0, 0.0]
radius = 1.03680
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.cones]]
id = "cone1"
color = [250, 250, 0]
position = [15.52365, 6.82361, 18.79629]
dir = [0.23681, -0.35846, 0.90301]
radius = 1.31265
height = 2.62529
reflective = true
rotatable = true
movable = false
scorable = true
transparent = false

[[objects.cones]]
id = "cone2"
color = [0, 250, 0]
position = [-8.15027, 2.57998, 24.57674]
dir = [-0.02888, 0.99956, -0.00612]
radius = 1.30680
height = 2.61360
reflective = true
rotatable = true
movable = true
scorable = true
transparent = false

[[objects.cones]]
id = "cone3"
color = [250, 0, 0]
position = [9.67083, 8.84342, 19.83250]
dir = [-0.11760, -0.99300, 0.01100]
radius = 2.33846
height = 4.67692
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[beam.sources]]
id = "beam_source1"
intensity = 1
position = [-1.18481, 15.31800, -6.19534]
dir = [0.99103, 0.13307, -0.01250]
color = [255, 255, 255]
radius = 1
length = 51
movable = false
rotatable = false
scorable = false
with_laser = true

[[beam.targets]]
id = "beam_target1"
position = [16.60091, 17.98289, 20.99676]
color = [255, 255, 255]
radius = 3
movable = false
scorable = false

