[quota]
target = true
minimal_score = 5.0

[camera]
id = "camera"
position = [-5.87642, 20.90787, 11.15270]
lookdir = [0.74469, -0.61734, -0.25363]
fov = 120

[lighting.ambient]
intensity = 0.40000
color = [255, 255, 255]

[[objects.planes]]
id = "plane1"
color = [170, 170, 170]
position = [0, 21.55000, 0]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane2"
color = [80, 80, 80]
texture = "textures/floor.jpg"
position = [-26.36382, 0.81532, -47.83988]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane3"
color = [133, 116, 95]
position = [5.97069, 5.01130, 26.11128]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane4"
color = [133, 116, 95]
position = [-10, 0, 0]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane5"
color = [133, 116, 95]
position = [20.35066, 16.73787, -1.16790]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane6"
color = [133, 116, 95]
position = [-4.57157, -0.09982, -9.42990]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.boxes]]
id = "box1"
color = [128, 128, 128]
position = [17.03844, 17.44672, 16.45691]
dir = [0, 1, 0]
width = 13.31000
height = 13.31000
length = 0.26620
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.boxes]]
id = "box2"
color = [0, 250, 0]
position = [14.33430, 18.03914, -6.67915]
dir = [-0.02180, -0.58492, -0.81080]
width = 1.46410
height = 1.46410
length = 1.46410
reflective = true
rotatable = true
movable = true
scorable = true
transparent = false

[[objects.boxes]]
id = "box3"
color = [250, 250, 0]
position = [-7.91574, 18.83941, 23.16119]
dir = [0.15590, 0.98002, 0.12348]
width = 1.82439
height = 1.82439
length = 1.82439
reflective = true
rotatable = true
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere1"
color = [250, 0, 0]
position = [14.11028, 6.65264, 1.85324]
dir = [0.0, 1.0, 0.0]
radius = 1
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere2"
color = [250, 0, 0]
position = [2.58201, 7.66485, 1.79933]
dir = [0.0, 1.0, 0.0]
radius = 1
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere3"
color = [250, 0, 0]
position = [15.23746, 11.49689, 11.64396]
dir = [0.0, 1.0, 0.0]
radius = 1.03680
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere4"
color = [250, 0, 0]
position = [7.43902, 8.21789, 8.31929]
dir = [0.0, 1.0, 0.0]
radius = 1.03680
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere5"
color = [250, 0, 0]
position = [-1.01901, 13.99686, 8.48670]
dir = [0.0, 1.0, 0.0]
radius = 1.03680
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.spheres]]
id = "sphere6"
color = [250, 0, 0]
position = [-1.36022, 10.34180, 16.27268]
dir = [0.0, 1.0, 0.0]
radius = 1.03680
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.cones]]
id = "cone1"
color = [250, 250, 0]
position = [15.24659, 8.93429, 20.52308]
dir = [-0.38548, 0.19232, 0.90245]
radius = 1.31265
height = 2.62529
reflective = true
rotatable = true
movable = false
scorable = true
transparent = false

[[objects.cones]]
id = "cone2"
color = [0, 250, 0]
position = [-6.91864, 2.80891, 23.89114]
dir = [-0.03480, 0.99931, 0.01267]
radius = 1.30680
height = 2.61360
reflective = true
rotatable = true
movable = true
scorable = true
transparent = false

[[objects.cones]]
id = "cone3"
color = [250, 0, 0]
position = [9.67083, 8.84342, 19.83250]
dir = [-0.11760, -0.99300, 0.01100]
radius = 2.33846
height = 4.67692
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[beam.sources]]
id = "beam_source1"
intensity = 1
position = [-1.06249, 15.41634, -6.24531]
dir = [0.99048, 0.13701, -0.01355]
color = [255, 255, 255]
radius = 1
length = 51
movable = false
rotatable = false
scorable = false
with_laser = true

[[beam.targets]]
id = "beam_target1"
position = [16.60091, 17.98289, 20.99676]
color = [255, 255, 255]
radius = 3
movable = false
scorable = false

