[camera]
id = "camera"
position = [0.0, 0.0, -6.0]
lookdir = [0.0, 0.0, 1.0]
fov = 120.0

[lighting.ambient]
intensity = 0.2
color = [255, 255, 255]

[[lighting.light_sources]]
id = "light1"
intensity = 1.0
position = [5.0, -2.0, -10.0]
color = [255, 255, 255]

[[objects.cones]]
id = "cone1"
color = [0, 255, 1]
position = [2.0, 0.0, 0.0]
dir = [0.0, -1.0, 0.0]
radius = 3.0
height = 3.0
reflective = true
rotatable = true
movable = true
scorable = false
transparent = false

[[objects.spheres]]
id = "sphere1"
color = [255, 0, 0]
position = [-2.0, -0.4, 0.0]
dir = [0.0, 1.0, 0.0]
radius = 1.0
reflective = true
rotatable = true
movable = false
scorable = false
transparent = false

[[objects.cylinders]]
id = "cylinder1"
color = [100, 0, 255]
position = [0.0, 3.0, 0.0]
dir = [0.70710, -0.70710, 0.0]
radius = 1.0
height = 3.0
reflective = false
rotatable = true
movable = true
scorable = false
transparent = true

[[objects.boxes]]
id = "box1"
color = [200, 200, 200]
position = [0.0, -5.0, 0.0]
dir = [0.0, 1.0, 0.0]
width = 2.0
height = 2.0
length = 2.0
reflective = true
rotatable = true
movable = true
scorable = false
transparent = false

[[objects.planes]]
id = "floor"
color = [50, 50, 50]
position = [0.0, -10.0, 0.0]
dir = [0.0, 1.0, 0.0]
reflective = false
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.planes]]
id = "ceiling"
color = [150, 150, 150]
position = [-15.0, 10.0, 0.0]
dir = [0.0, 1.0, 0.0]
reflective = false
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.planes]]
id = "back_wall"
color = [50, 50, 50]
position = [0.0, -10.0, 10.0]
dir = [0.0, 0.0, -1.0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "left_wall"
color = [0, 100, 0]
position = [-10.0, 0.0, 10.0]
dir = [1.0, 0.0, 0.0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "right_wall"
color = [0, 0, 100]
position = [10.0, 0.0, 10.0]
dir = [1.0, 0.0, 0.0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[beam.sources]]
id = "beam_source1"
intensity = 0.75
position = [1.1, 1.1, -3.4]
dir = [0.0, 0.0, 1.0]
color = [255, 0, 255]
radius = 0.08
length = 20.0
movable = true
rotatable = true
scorable = true
with_laser = false

[[beam.targets]]
id = "beam_target1"
position = [1.1, 1.1, 0.0]
color = [255, 255, 0]
radius = 0.4
movable = false
scorable = true

[quota]
target = true
minimal_score = 2.0
