[quota]
target = true
minimal_score = 3.0

[camera]
id = "camera"
position = [8.05309, 5.44287, -29.18574]
lookdir = [-0.29190, -0.46886, 0.83365]
fov = 120

[lighting.ambient]
intensity = 0.50000
color = [255, 255, 255]

[[objects.planes]]
id = "plane1"
color = [170, 170, 170]
position = [0, 10, 0]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane2"
color = [80, 80, 80]
position = [0, -10, 0]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane3"
color = [133, 116, 95]
position = [0, 0, 10]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane4"
color = [133, 116, 95]
position = [-10, 0, 0]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane5"
color = [133, 116, 95]
position = [10, 0, 0]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane6"
color = [133, 116, 95]
position = [0, 0, -30]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.boxes]]
id = "box1"
color = [255, 255, 0]
position = [-4.46192, 3.46111, -4.29934]
dir = [0.09627, 0.49138, 0.86561]
width = 1
height = 3
length = 2
reflective = true
rotatable = true
movable = false
scorable = true
transparent = false

[[beam.sources]]
id = "beam_source1"
intensity = 1
position = [1.06517, 2.62323, -22.16474]
dir = [-0.28604, 0.04312, 0.95725]
color = [255, 255, 255]
radius = 1.30000
length = 40
movable = false
rotatable = false
scorable = false
with_laser = true

[[beam.targets]]
id = "beam_target1"
position = [3.84572, -1.44382, 2.38892]
color = [255, 255, 255]
radius = 1.30000
movable = false
scorable = false

