[prompts]
a = "The goal of the game is use objects on the map to lead the `laser` to the `Beam Target` and get the minimal `score` required to pass the level."
b = "Reach the quota (`top left corner`) to clear the level or optimize your setup to climb the leaderboard!"

[quota]
target = true
minimal_score = 3

[camera]
id = "camera"
position = [7.88532, 5.58000, -27.31092]
lookdir = [-0.46222, -0.27058, 0.84447]
fov = 120

[lighting.ambient]
intensity = 0.70000
color = [201, 255, 245]

[[objects.planes]]
id = "plane1"
color = [200, 200, 200]
position = [0, 10, 0]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane2"
color = [80, 80, 80]
position = [0, -3.34000, 0]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane3"
color = [136, 150, 165]
position = [0, 0, 10]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane4"
color = [136, 150, 165]
position = [-10, 0, 0]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane5"
color = [136, 150, 165]
position = [10, 0, 0]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane6"
color = [136, 150, 165]
position = [0, 0, -30]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.boxes]]
id = "box1"
color = [255, 255, 0]
position = [-4.46192, 3.46111, -4.29934]
dir = [0.09627, 0.49138, 0.86561]
width = 1
height = 3
length = 2
reflective = true
rotatable = true
movable = false
scorable = true
transparent = false

[[beam.sources]]
id = "beam_source1"
intensity = 1
position = [1.06517, 2.62323, -22.16474]
dir = [-0.28604, 0.04312, 0.95725]
color = [255, 255, 255]
radius = 1.30000
length = 40
movable = false
rotatable = false
scorable = false
with_laser = true

[[beam.targets]]
id = "beam_target1"
position = [3.84572, -1.44382, 2.38892]
color = [255, 255, 255]
radius = 1.30000
movable = false
scorable = false

