[prompts]
a = "Objects can have different shapes and colors.\nColor of the object determines the way you can interact with it."
b = "Green objects can be both moved and rotated.\nYellow objects can be rotated but can't be moved.\nRed objects stay put - you can't move or rotate them.\nGrey objects don't score points and can't be moved or rotated."

[camera]
id = "camera"
position = [3.31039, -2.10638, -16.69617]
lookdir = [-0.08381, -0.34288, 0.93563]
fov = 120

[lighting.ambient]
intensity = 0.70000
color = [201, 255, 245]

[[objects.planes]]
id = "plane1"
color = [200, 200, 200]
position = [-5.78242, 2.55023, -1.69474]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane2"
color = [80, 80, 80]

position = [10.87668, -8.09944, 6.45878]
dir = [0, 1, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane3"
color = [136,150,165]
position = [-1.89363, 0.13519, 1.01673]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane4"
color = [136,150,165]
position = [-9.15730, 0.20377, -7.25503]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane5"
color = [136,150,165]
position = [11.40453, -0.22433, 0.49850]
dir = [1, 0, 0]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.planes]]
id = "plane6"
color = [136,150,165]
position = [11.07437, 3.13255, -24.87391]
dir = [0, 0, -1]
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.boxes]]
id = "box1"
color = [128, 128, 128]
position = [6.66480, -4.0, -10.0]
dir = [0.0, 1.0, 0.0]
width = 1.75385
height = 1.75385
length = 1.75385
reflective = false
rotatable = false
movable = false
scorable = false
transparent = false

[[objects.spheres]]
id = "sphere1"
color = [255, 0, 0]
position = [2.99261, -4.0, -10.0]
dir = [0.0, 1.0, 0.0]
radius = 1
reflective = true
rotatable = false
movable = false
scorable = true
transparent = false

[[objects.cones]]
id = "cone1"
color = [255, 255, 0]
position = [-1.04205, -4.0, -10.0]
dir = [0.0, 1.0, 0.0]
radius = 1
height = 2
reflective = true
rotatable = true
movable = false
scorable = true
transparent = false

[[objects.cylinders]]
id = "cylinder1"
color = [0, 255, 0]
position = [-4.31025, -4.0, -10.0]
dir = [0.0, 1.0, 0.0]
radius = 0.5
height = 2
reflective = true
rotatable = true
movable = true
scorable = true
transparent = false

